name: carbonlens_app_01
description: "CarbonLens แอพคำนวณการดูดซับคาร์บอนของต้นไม้"

publish_to: 'none' # ลบหรือคงไว้ตามความต้องการ

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0  
  get: ^4.6.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7 # หรือเวอร์ชันล่าสุด

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

